version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: TP_LENGUAJE_II
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
      