package vista;

import java.awt.Component;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

import controlador.ComputadoresControl;
import modelo.Computador;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;

public class FrmComputadores extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	ComputadoresControl computadoresControl = new ComputadoresControl();
    Computador computador = null;
    public static final int SI = 0;
    public static final int NO = 1;
    public static final int CANCELAR = 2;

    public FrmComputadores() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.refresh();
    }

    public void refresh() {
    	List<Computador> computadoresList = new ArrayList<>();
    	DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Garantia");
        modelo.addColumn("Duracion");
        
        computadoresList = computadoresControl.listar("");
        Object[] fila = new Object[6];

        for (int i = 0; i < computadoresList.size(); i++) {
            computador = (Computador) computadoresList.get(i);
            fila[0] = computador.getCodigo();
            fila[1] = computador.getNombre();
            fila[2] = computador.getDescripcion();
            fila[3] = computador.getPrecio();
            fila[4] = computador.isTieneGarantia() ? "SI": "NO";
            fila[5] = computador.getDuracionGarantia();
            modelo.addRow(fila);
        }

        tblComputadores.setModel(modelo);

        limpiar();

    }

    public void limpiar() {
    	lblId.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
        txtGarantia.setText("");
        btngrabar.setText("Grabar");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComputadores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setAlignmentY(Component.TOP_ALIGNMENT);
        lblGarantia = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtGarantia =new javax.swing.JTextField();
        txtGarantia.setEnabled(false); //default
        chckbxTieneGarantia= new JCheckBox("Tiene Garantia ?");
        onChangeChckbxTieneGarantia();
        
        btngrabar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnModificar = new javax.swing.JMenuItem();
        btnEliminar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computadores - EV. Informatica");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        tblComputadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo","Nombre", "Descripcion", "Precio", "Garantia"
            }
        ));
        jScrollPane1.setViewportView(tblComputadores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Descripcion:");

        jLabel3.setText("Precio:");
        
        lblGarantia.setText("Duración Garantía");
        
        btngrabar.setText("Grabar");
        btngrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngrabarActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(txtNombre, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(txtDescripcion, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        				.addComponent(txtPrecio, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtGarantia, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE))
        			.addGap(18))
        		.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        			.addGap(6)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(chckbxTieneGarantia)
        				.addComponent(jLabel3)
        				.addComponent(jLabel2)
        				.addComponent(jLabel1)
        				.addComponent(lblGarantia, GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
        			.addGap(59)
        			.addComponent(lblId)
        			.addContainerGap(18, Short.MAX_VALUE))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(160, Short.MAX_VALUE)
        			.addComponent(btngrabar))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(lblId))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtDescripcion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(txtPrecio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(chckbxTieneGarantia)
        			.addGap(18)
        			.addComponent(lblGarantia)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtGarantia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(btngrabar)
        			.addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {txtNombre, txtDescripcion, txtPrecio, txtGarantia});
        jPanel2.setLayout(jPanel2Layout);

        jMenu3.setText("Archivo");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jMenu3.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jMenu3.add(btnEliminar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void onChangeChckbxTieneGarantia() {
		chckbxTieneGarantia.addChangeListener(new ChangeListener() {
        	public void stateChanged(ChangeEvent arg0) {
        			txtGarantia.setEnabled(chckbxTieneGarantia.isSelected());
        		
        	}
        });
	}

    private void btngrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngrabarActionPerformed

        Integer id = null;
        String nombre = txtNombre.getText();
        String descripcion = txtDescripcion.getText();
        String precioStr = txtPrecio.getText();
        BigDecimal precio = null;
        boolean tieneGarantia = chckbxTieneGarantia.isSelected();
        String duracionGarantia = txtGarantia.getText();
        String mensaje = "";
        
        try {
            precio = new BigDecimal(precioStr);
            if(lblId.getText() != null && !lblId.getText().isEmpty())
            {
             id = Integer.parseInt(lblId.getText());
            }     
            computador = new Computador(id, nombre, descripcion, precio, tieneGarantia,duracionGarantia);
            
            if(computador.getCodigo() != null)
            {
                //UPDATE
                computadoresControl.modificar(computador);
                mensaje = "modificado";
            }else{
                //INSERT
            	computadoresControl.insertar(computador);
                mensaje = "insertado";
            }
            
            this.refresh();

            JOptionPane.showMessageDialog(null, "Se ha "+mensaje+" con exito");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Edad y Peso son numericos y obligatorios");
        }


    }//GEN-LAST:event_btngrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    	List<Computador> computadoresList = new ArrayList<>();
        Integer filaNum = tblComputadores.getSelectedRow();

        if (filaNum<0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        } else {
            DefaultTableModel modelo = (DefaultTableModel) tblComputadores.getModel();

            Integer id = (Integer) modelo.getValueAt(filaNum, 0);
            computadoresList = computadoresControl.listar("WHERE codigo='" + id + "'");
			computador = (Computador) computadoresList.get(0);

            //me aseguro de limpiar antes de cambiar
            limpiar();

            lblId.setText(computador.getCodigo().toString());

            txtNombre.setText(computador.getNombre());
            txtDescripcion.setText(computador.getDescripcion());
            txtPrecio.setText(computador.getPrecio().toString());
            txtGarantia.setText(computador.getDuracionGarantia());
            chckbxTieneGarantia.setSelected(computador.isTieneGarantia());

            btngrabar.setText("Modificar");
        }


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    	List<Computador> computadoresList = new ArrayList<>();
    	Integer filaNum = tblComputadores.getSelectedRow();

        if (filaNum<0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        } else {
            int input = JOptionPane.showConfirmDialog(null, "Desea Eliminar el Objeto?");
            
            

            switch (input) {
                case SI:
                    DefaultTableModel modelo = (DefaultTableModel) tblComputadores.getModel();
                    Integer id = (Integer) modelo.getValueAt(filaNum, 0);
                    computadoresList = computadoresControl.listar("WHERE codigo='" + id + "'");
                    computador = (Computador) computadoresList.get(0);
                    
                    computadoresControl.eliminar(computador);
                    break;
                case NO:
                    JOptionPane.showMessageDialog(null, "Sabia decision");
                    break;
                case CANCELAR:
                   JOptionPane.showMessageDialog(null, "Evento Cancelado");
                    break;
            }
            this.refresh();
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComputadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmComputadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JMenuItem btnModificar;
    private javax.swing.JButton btngrabar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tblComputadores;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JCheckBox chckbxTieneGarantia;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JTextField txtGarantia;
    
}
